apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: helmreleases.helm.toolkit.fluxcd.io
spec:
  group: helm.toolkit.fluxcd.io
  names:
    kind: HelmRelease
    plural: helmreleases
    singular: helmrelease
  scope: Namespaced
  versions:
    - name: v2beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
